In [1]:
import numpy as np
import pandas as pd

In [2]:
df_2021 = pd.read_csv('world-happiness-report-2021.csv')

In [3]:
df_history = pd.read_csv('world-happiness-report.csv')

In [4]:
df_2021.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [5]:
df_history.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [6]:
df1_2021 = df_2021[['Country name', 'Regional indicator', 'Ladder score',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']].copy()

# df1_2021 sütunlarını (isimleri birebir aynı olmasa da) df_history ile eşitledik ve bunu yeni bir tabloya bu halini eşitledik.

In [9]:
df_history.head(1)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.37,0.451,50.8,0.718,0.168,0.882,0.518,0.258

In [10]:
history_df = df_history[['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']].copy()

# positive affect ve negative affect sütunları işimize yaramadığı için onları düşürdük yeni bir tabloya bu halini eşitledik.

In [11]:
history_df.head(1)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2008,3.724,7.37,0.451,50.8,0.718,0.168,0.882

In [12]:
df1_2021.rename(columns = {'Ladder score':'Life Ladder', 'Logged GDP per capita':'Log GDP per capita', 'Healthy life expectancy': 'Healthy life expectancy at birth', }, inplace=True)

In [13]:
df1_2021.head(1)

# year sütunu yoktu. aşağıdaki line ı önce çalıştırdığım için burda gözüküyor. normalde yok.

,Country name,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186

In [14]:
df1_2021['year'] = 2021

# history ile eşit olsun diye year sütununu da ekledik ve içine 2021 değerini atadık.

In [12]:
df1_2021.head(1)

,Country name,Regional indicator,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186,2021

In [16]:
df1_2021['Regional indicator'].value_counts()

# Önce Regional indicatorları görelim. bu sütun df1_2021 deydi. daha sonra bunu history'e ekleyeceğiz

Sub-Saharan Africa                    36
Western Europe                        21
Latin America and Caribbean           20
Middle East and North Africa          17
Central and Eastern Europe            17
Commonwealth of Independent States    12
Southeast Asia                         9
South Asia                             7
East Asia                              6
North America and ANZ                  4
Name: Regional indicator, dtype: int64

In [15]:
df_north = df1_2021[df1_2021["Regional indicator"] == "North America and ANZ"]
df_north

,Country name,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
8,New Zealand,North America and ANZ,7.277,10.643,0.948,73.4,0.929,0.134,0.242,2021
10,Australia,North America and ANZ,7.183,10.796,0.940,73.9,0.914,0.159,0.442,2021
13,Canada,North America and ANZ,7.103,10.776,0.926,73.8,0.915,0.089,0.415,2021
18,United States,North America and ANZ,6.951,11.023,0.920,68.2,0.837,0.098,0.698,2021

In [17]:
df_north["Country name"].to_list()

# df_north datasetindeki ülkeleri listeye aldık. sonra bu listeleri df_history datasetinde 
# region indicatorları belirlerken kullanacağız                                                                                                                                                                                                                                                                                           Regional indicator sütununu oluştururken

['New Zealand', 'Australia', 'Canada', 'United States']

In [18]:
western = df1_2021[df1_2021['Regional indicator'] == 'Western Europe']
western

,Country name,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,Western Europe,7.842,10.775,0.954,72.000,0.949,-0.098,0.186,2021
1,Denmark,Western Europe,7.620,10.933,0.954,72.700,0.946,0.030,0.179,2021
2,Switzerland,Western Europe,7.571,11.117,0.942,74.400,0.919,0.025,0.292,2021
3,Iceland,Western Europe,7.554,10.878,0.983,73.000,0.955,0.160,0.673,2021
4,Netherlands,Western Europe,7.464,10.932,0.942,72.400,0.913,0.175,0.338,2021
5,Norway,Western Europe,7.392,11.053,0.954,73.300,0.960,0.093,0.270,2021
6,Sweden,Western Europe,7.363,10.867,0.934,72.700,0.945,0.086,0.237,2021
7,Luxembourg,Western Europe,7.324,11.647,0.908,72.600,0.907,-0.034,0.386,2021
9,Austria,Western Europe,7.268,10.906,0.934,73.300,0.908,0.042,0.481,2021
12,Germany,Western Europe,7.155,10.873,0.903,72.500,0.875,0.011,0.460,2021
14,Ireland,Western Europe,7.085,11.342,0.947,72.400,0.879,0.077,0.363,2021
16,United Kingdom,Western Europe,7.064,10.707,0.934,72.500,0.859,0.233,0.459,2021
19,Belgium,Western Europe,6.834,10.823,0.906,72.199,0.783,-0.153,0.646,2021
20,France,Western Europe,6.690,10.704,0.942,74.000,0.822,-0.147,0.571,2021
22,Malta,Western Europe,6.602,10.674,0.931,72.200,0.927,0.133,0.653,2021
26,Spain,Western Europe,6.491,10.571,0.932,74.700,0.761,-0.081,0.745,2021
27,Italy,Western Europe,6.483,10.623,0.880,73.800,0.693,-0.084,0.866,2021
38,Cyprus,Western Europe,6.223,10.576,0.802,73.898,0.763,-0.015,0.844,2021
57,Portugal,Western Europe,5.929,10.421,0.879,72.600,0.892,-0.244,0.887,2021
67,Greece,Western Europe,5.723,10.279,0.823,72.600,0.582,-0.288,0.823,2021
73,North Cyprus,Western Europe,5.536,10.576,0.820,73.898,0.795,0.012,0.626,2021

In [19]:
western["Country name"].to_list()

# bunun gibi diğer tüm bölgelerdeki ülkeleri de bulacağız.

['Finland',
 'Denmark',
 'Switzerland',
 'Iceland',
 'Netherlands',
 'Norway',
 'Sweden',
 'Luxembourg',
 'Austria',
 'Germany',
 'Ireland',
 'United Kingdom',
 'Belgium',
 'France',
 'Malta',
 'Spain',
 'Italy',
 'Cyprus',
 'Portugal',
 'Greece',
 'North Cyprus']

In [19]:
df_north = df1_2021[df1_2021['Regional indicator'] == 'North America and ANZ']
df_north['Country name']

# alttaki fonksiyonu oluşturmak için bilgileri nerden aldığımızı çalıştık.

8       New Zealand
10        Australia
13           Canada
18    United States
Name: Country name, dtype: object

In [20]:
df_north['Country name'].to_list()

# aşağıdaki listeyi şimdi alıp fonksiyonda yerine koyabiliriz.
# bunun yerine yukardan kopyala yapıştır da yapabilirdik kolaylık olsun diye to_list() metodu kullandık.

['New Zealand', 'Australia', 'Canada', 'United States']

In [22]:
def region(country):
    if country in ['Mauritius','Congo (Brazzaville)','Ivory Coast','Cameroon','Senegal','Ghana','Niger','Gambia','Benin','Guinea','South Africa','Gabon','Burkina Faso','Mozambique','Nigeria','Mali','Uganda','Liberia','Kenya','Namibia','Chad','Swaziland','Comoros','Ethiopia','Mauritania','Madagascar','Togo','Zambia', 'Sierra Leone','Burundi','Tanzania','Malawi','Lesotho','Botswana','Rwanda','Zimbabwe']:
        return 'Sub-Saharan Africa'
    elif country in ['Finland','Denmark','Switzerland','Iceland','Netherlands','Norway','Sweden','Luxembourg','Austria','Germany','Ireland','United Kingdom','Belgium','France','Malta','Spain','Italy','Cyprus','Portugal','Greece','North Cyprus']:
        return 'Western Europe'
    elif country in ['Costa Rica','Guatemala','Uruguay','Brazil','Mexico','Jamaica','Panama','Chile','El Salvador','Colombia','Nicaragua','Argentina','Honduras','Peru','Ecuador','Bolivia','Paraguay','Dominican Republic','Venezuela','Haiti']:
        return 'Latin America and Caribbean'
    elif country in ['Israel','Bahrain','United Arab Emirates','Saudi Arabia','Kuwait','Libya','Turkey','Morocco','Algeria','Iraq','Iran','Tunisia','Lebanon','Palestinian Territories','Jordan','Egypt','Yemen']:
        return 'Middle East and North Africa'
    elif country in ['Czech Republic','Slovenia','Kosovo','Slovakia','Lithuania','Estonia','Poland','Romania','Serbia','Latvia','Hungary','Croatia','Bosnia and Herzegovina','Montenegro', 'Bulgaria','Albania','North Macedonia']:
        return 'Central and Eastern Europe'
    elif country in ['Uzbekistan','Kazakhstan','Moldova','Kyrgyzstan','Belarus','Russia','Tajikistan','Armenia','Azerbaijan','Turkmenistan','Georgia','Ukraine']:
        return 'Commonwealth of Independent States'
    elif country in ['Singapore','Thailand','Philippines','Vietnam','Malaysia','Indonesia','Laos','Cambodia','Myanmar']:
        return 'Southeast Asia'
    elif country in ['Nepal','Maldives','Bangladesh','Pakistan','Sri Lanka','India','Afghanistan']:
        return 'South Asia'
    elif country in ['Taiwan Province of China','Japan','South Korea','Mongolia','Hong Kong S.A.R. of China','China']:
        return 'East Asia'
    elif country in ['New Zealand', 'Australia', 'Canada', 'United States']:
        return 'North America and ANZ'

In [23]:
history_df['Regional indicator'] = history_df['Country name'].apply(region)

history_df

# Regional indicator sütunu oluşturup buna history_df'in country name lerini region fonksiyonuna uygulayarak burdan return olan 
# regionları ona atadık. (fonksiyondaki country parametresine country name değerleri giriyor ve region return oluyor.)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,South Asia
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,South Asia
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,South Asia
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,South Asia
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,South Asia
...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,Sub-Saharan Africa
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,Sub-Saharan Africa
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,Sub-Saharan Africa
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,Sub-Saharan Africa
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,Sub-Saharan Africa

In [23]:
# şimdi df_2021 üzerinde çalışıyoruz. sonra df_2021 i df_history'e ekleyeceğiz

df_sub_saharan = df1_2021[df1_2021["Regional indicator"]=="Sub-Saharan Africa"]
df_sub_saharan

# bunun gibi diğer tüm regionları da yapıyoruz

,Country name,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
49,Mauritius,Sub-Saharan Africa,6.049,10.008,0.905,66.701,0.867,-0.054,0.789,2021
82,Congo (Brazzaville),Sub-Saharan Africa,5.342,8.117,0.636,58.221,0.695,-0.068,0.745,2021
84,Ivory Coast,Sub-Saharan Africa,5.306,8.551,0.644,50.114,0.741,-0.016,0.794,2021
90,Cameroon,Sub-Saharan Africa,5.142,8.189,0.710,53.515,0.731,0.026,0.848,2021
91,Senegal,Sub-Saharan Africa,5.132,8.118,0.710,59.802,0.695,-0.046,0.801,2021
94,Ghana,Sub-Saharan Africa,5.088,8.580,0.727,57.586,0.807,0.123,0.848,2021
95,Niger,Sub-Saharan Africa,5.074,7.098,0.641,53.780,0.806,0.018,0.693,2021
97,Gambia,Sub-Saharan Africa,5.051,7.686,0.690,55.160,0.697,0.424,0.746,2021
98,Benin,Sub-Saharan Africa,5.045,8.087,0.489,54.713,0.757,-0.034,0.661,2021
101,Guinea,Sub-Saharan Africa,4.984,7.838,0.639,55.008,0.697,0.095,0.766,2021
102,South Africa,Sub-Saharan Africa,4.956,9.403,0.860,56.904,0.749,-0.067,0.860,2021
111,Gabon,Sub-Saharan Africa,4.852,9.603,0.776,59.962,0.731,-0.200,0.840,2021
112,Burkina Faso,Sub-Saharan Africa,4.834,7.678,0.672,54.151,0.695,-0.009,0.748,2021
114,Mozambique,Sub-Saharan Africa,4.794,7.158,0.744,54.706,0.882,0.061,0.684,2021
115,Nigeria,Sub-Saharan Africa,4.759,8.533,0.740,50.102,0.737,0.037,0.878,2021
116,Mali,Sub-Saharan Africa,4.723,7.744,0.724,51.969,0.697,-0.036,0.827,2021
118,Uganda,Sub-Saharan Africa,4.636,7.677,0.781,56.101,0.709,0.122,0.855,2021
119,Liberia,Sub-Saharan Africa,4.625,7.288,0.720,56.498,0.735,0.050,0.850,2021
120,Kenya,Sub-Saharan Africa,4.607,8.361,0.688,60.704,0.779,0.287,0.825,2021
123,Namibia,Sub-Saharan Africa,4.574,9.161,0.818,56.799,0.719,-0.149,0.847,2021
127,Chad,Sub-Saharan Africa,4.355,7.364,0.619,48.478,0.579,0.041,0.807,2021
129,Swaziland,Sub-Saharan Africa,4.308,9.065,0.770,50.833,0.647,-0.185,0.708,2021
130,Comoros,Sub-Saharan Africa,4.289,8.031,0.626,57.349,0.548,0.082,0.781,2021
132,Ethiopia,Sub-Saharan Africa,4.275,7.694,0.764,59.000,0.752,0.082,0.761,2021
133,Mauritania,Sub-Saharan Africa,4.227,8.542,0.795,57.161,0.561,-0.106,0.731,2021
134,Madagascar,Sub-Saharan Africa,4.208,7.396,0.686,59.305,0.552,-0.005,0.803,2021
135,Togo,Sub-Saharan Africa,4.107,7.362,0.569,54.914,0.619,0.032,0.772,2021
136,Zambia,Sub-Saharan Africa,4.073,8.145,0.708,55.809,0.782,0.061,0.823,2021
137,Sierra Leone,Sub-Saharan Africa,3.849,7.434,0.630,51.651,0.717,0.084,0.866,2021
139,Burundi,Sub-Saharan Africa,3.775,6.635,0.490,53.400,0.626,-0.024,0.607,2021
141,Tanzania,Sub-Saharan Africa,3.623,7.876,0.702,57.999,0.833,0.183,0.577,2021
143,Malawi,Sub-Saharan Africa,3.600,6.958,0.537,57.948,0.780,0.038,0.729,2021
144,Lesotho,Sub-Saharan Africa,3.512,7.926,0.787,48.700,0.715,-0.131,0.915,2021
145,Botswana,Sub-Saharan Africa,3.467,9.782,0.784,59.269,0.824,-0.246,0.801,2021
146,Rwanda,Sub-Saharan Africa,3.415,7.676,0.552,61.400,0.897,0.061,0.167,2021
147,Zimbabwe,Sub-Saharan Africa,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,2021

In [24]:
df_north = df1_2021[df_2021["Regional indicator"] == 'North America and ANZ']
df_north

# diğer bölgeleri de aynı komutla değişkenlere atıyoruz.

,Country name,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
8,New Zealand,North America and ANZ,7.277,10.643,0.948,73.4,0.929,0.134,0.242,2021
10,Australia,North America and ANZ,7.183,10.796,0.940,73.9,0.914,0.159,0.442,2021
13,Canada,North America and ANZ,7.103,10.776,0.926,73.8,0.915,0.089,0.415,2021
18,United States,North America and ANZ,6.951,11.023,0.920,68.2,0.837,0.098,0.698,2021

In [26]:
df_sub_saharan = df1_2021[df1_2021["Regional indicator"] == "Sub-Saharan Africa"]

In [28]:
df_west = df1_2021[df1_2021["Regional indicator"] == "Western Europe"]

In [29]:
df_latin=df1_2021[df1_2021['Regional indicator']=='Latin America and Caribbean']

In [30]:
df_middle_east=df1_2021[df1_2021['Regional indicator']=='Middle East and North Africa']

In [31]:
df_central=df1_2021[df1_2021['Regional indicator']=='Central and Eastern Europe']

In [32]:
df_commonwealth=df1_2021[df1_2021['Regional indicator']=='Commonwealth of Independent States']

In [33]:
df_Southeast=df1_2021[df1_2021['Regional indicator']=='Southeast Asia']

In [34]:
df_South=df1_2021[df1_2021['Regional indicator']=='South Asia']

In [35]:
df_East=df1_2021[df1_2021['Regional indicator']=='East Asia']

In [62]:
df_north = df1_2021[df1_2021['Regional indicator']=='North America and ANZ']

In [ ]:
# şimdi append yöntemi ile Türkiye satırını diğer datasetine ekleyeceğiz.

In [37]:
history_df = history_df.append([df_sub_saharan,df_west,df_latin,df_middle_east,df_central,df_commonwealth,df_Southeast,df_South,df_East,df_north],ignore_index = True)

# yukarda tanımladığımız tüm regionlarıhistory_df'e appende yapıp bunu kendisine eşitledik ki kalıcı olsun.

# 2. soru cevabı:

In [40]:
history_df[history_df["Regional indicator"] == "Sub-Saharan Africa"].groupby("Country name")[["Life Ladder", "Freedom to make life choices", "Perceptions of corruption"]].describe()

# Regional indicator'ı Sub-sahatran africa olanları "country name" lere göre grupla 
# ve sağda belirtilen sütunların ("Life Ladder", "Freedom to make life choices", "Perceptions of corruption")
# describe bilgilerini göster.

                    Life Ladder                                                \
                          count   mean std    min    25%    50%    75%    max
Country name
Benin                       1.0  5.045 NaN  5.045  5.045  5.045  5.045  5.045
Botswana                    1.0  3.467 NaN  3.467  3.467  3.467  3.467  3.467
Burkina Faso                1.0  4.834 NaN  4.834  4.834  4.834  4.834  4.834
Burundi                     1.0  3.775 NaN  3.775  3.775  3.775  3.775  3.775
Cameroon                    1.0  5.142 NaN  5.142  5.142  5.142  5.142  5.142
Chad                        1.0  4.355 NaN  4.355  4.355  4.355  4.355  4.355
Comoros                     1.0  4.289 NaN  4.289  4.289  4.289  4.289  4.289
Congo (Brazzaville)         1.0  5.342 NaN  5.342  5.342  5.342  5.342  5.342
Ethiopia                    1.0  4.275 NaN  4.275  4.275  4.275  4.275  4.275
Gabon                       1.0  4.852 NaN  4.852  4.852  4.852  4.852  4.852
Gambia                      1.0  5.051 NaN  5.051  5.051  5.051  5.051  5.051
Ghana                       1.0  5.088 NaN  5.088  5.088  5.088  5.088  5.088
Guinea                      1.0  4.984 NaN  4.984  4.984  4.984  4.984  4.984
Ivory Coast                 1.0  5.306 NaN  5.306  5.306  5.306  5.306  5.306
Kenya                       1.0  4.607 NaN  4.607  4.607  4.607  4.607  4.607
Lesotho                     1.0  3.512 NaN  3.512  3.512  3.512  3.512  3.512
Liberia                     1.0  4.625 NaN  4.625  4.625  4.625  4.625  4.625
Madagascar                  1.0  4.208 NaN  4.208  4.208  4.208  4.208  4.208
Malawi                      1.0  3.600 NaN  3.600  3.600  3.600  3.600  3.600
Mali                        1.0  4.723 NaN  4.723  4.723  4.723  4.723  4.723
Mauritania                  1.0  4.227 NaN  4.227  4.227  4.227  4.227  4.227
Mauritius                   1.0  6.049 NaN  6.049  6.049  6.049  6.049  6.049
Mozambique                  1.0  4.794 NaN  4.794  4.794  4.794  4.794  4.794
Namibia                     1.0  4.574 NaN  4.574  4.574  4.574  4.574  4.574
Niger                       1.0  5.074 NaN  5.074  5.074  5.074  5.074  5.074
Nigeria                     1.0  4.759 NaN  4.759  4.759  4.759  4.759  4.759
Rwanda                      1.0  3.415 NaN  3.415  3.415  3.415  3.415  3.415
Senegal                     1.0  5.132 NaN  5.132  5.132  5.132  5.132  5.132
Sierra Leone                1.0  3.849 NaN  3.849  3.849  3.849  3.849  3.849
South Africa                1.0  4.956 NaN  4.956  4.956  4.956  4.956  4.956
Swaziland                   1.0  4.308 NaN  4.308  4.308  4.308  4.308  4.308
Tanzania                    1.0  3.623 NaN  3.623  3.623  3.623  3.623  3.623
Togo                        1.0  4.107 NaN  4.107  4.107  4.107  4.107  4.107
Uganda                      1.0  4.636 NaN  4.636  4.636  4.636  4.636  4.636
Zambia                      1.0  4.073 NaN  4.073  4.073  4.073  4.073  4.073
Zimbabwe                    1.0  3.145 NaN  3.145  3.145  3.145  3.145  3.145

                    Freedom to make life choices         ...                \
                                           count   mean  ...    75%    max
Country name                                             ...
Benin                                        1.0  0.757  ...  0.757  0.757
Botswana                                     1.0  0.824  ...  0.824  0.824
Burkina Faso                                 1.0  0.695  ...  0.695  0.695
Burundi                                      1.0  0.626  ...  0.626  0.626
Cameroon                                     1.0  0.731  ...  0.731  0.731
Chad                                         1.0  0.579  ...  0.579  0.579
Comoros                                      1.0  0.548  ...  0.548  0.548
Congo (Brazzaville)                          1.0  0.695  ...  0.695  0.695
Ethiopia                                     1.0  0.752  ...  0.752  0.752
Gabon                                        1.0  0.731  ...  0.731  0.731
Gambia                                       1.0  0.697  ...  0.697  0.697
Ghana                                        1.0  0.807  ...  0.807  0.807
Guinea                                       1.0  0.697  ...  0.697  0.697
Ivory Coast                                  1.0  0.741  ...  0.741  0.741
Kenya                                        1.0  0.779  ...  0.779  0.779
Lesotho                                      1.0  0.715  ...  0.715  0.715
Liberia                                      1.0  0.735  ...  0.735  0.735
Madagascar                                   1.0  0.552  ...  0.552  0.552
Malawi                                       1.0  0.780  ...  0.780  0.780
Mali                                         1.0  0.697  ...  0.697  0.697
Mauritania                                   1.0  0.561  ...  0.561  0.561
Mauritius                                    1.0  0.867  ...  0.867  0.867
Mozambique                                   1.0  0.882  ...  0.882  0.882
Namibia                                      1.0  0.719  ...  0.719  0.719
Niger                                        1.0  0.806  ...  0.806  0.806
Nigeria                                      1.0  0.737  ...  0.737  0.737
Rwanda                                       1.0  0.897  ...  0.897  0.897
Senegal                                      1.0  0.695  ...  0.695  0.695
Sierra Leone                                 1.0  0.717  ...  0.717  0.717
South Africa                                 1.0  0.749  ...  0.749  0.749
Swaziland                                    1.0  0.647  ...  0.647  0.647
Tanzania                                     1.0  0.833  ...  0.833  0.833
Togo                                         1.0  0.619  ...  0.619  0.619
Uganda                                       1.0  0.709  ...  0.709  0.709
Zambia                                       1.0  0.782  ...  0.782  0.782
Zimbabwe                                     1.0  0.677  ...  0.677  0.677

                    Perceptions of corruption                                  \
                                        count   mean std    min    25%    50%
Country name
Benin                                     1.0  0.661 NaN  0.661  0.661  0.661
Botswana                                  1.0  0.801 NaN  0.801  0.801  0.801
Burkina Faso                              1.0  0.748 NaN  0.748  0.748  0.748
Burundi                                   1.0  0.607 NaN  0.607  0.607  0.607
Cameroon                                  1.0  0.848 NaN  0.848  0.848  0.848
Chad                                      1.0  0.807 NaN  0.807  0.807  0.807
Comoros                                   1.0  0.781 NaN  0.781  0.781  0.781
Congo (Brazzaville)                       1.0  0.745 NaN  0.745  0.745  0.745
Ethiopia                                  1.0  0.761 NaN  0.761  0.761  0.761
Gabon                                     1.0  0.840 NaN  0.840  0.840  0.840
Gambia                                    1.0  0.746 NaN  0.746  0.746  0.746
Ghana                                     1.0  0.848 NaN  0.848  0.848  0.848
Guinea                                    1.0  0.766 NaN  0.766  0.766  0.766
Ivory Coast                               1.0  0.794 NaN  0.794  0.794  0.794
Kenya                                     1.0  0.825 NaN  0.825  0.825  0.825
Lesotho                                   1.0  0.915 NaN  0.915  0.915  0.915
Liberia                                   1.0  0.850 NaN  0.850  0.850  0.850
Madagascar                                1.0  0.803 NaN  0.803  0.803  0.803
Malawi                                    1.0  0.729 NaN  0.729  0.729  0.729
Mali                                      1.0  0.827 NaN  0.827  0.827  0.827
Mauritania                                1.0  0.731 NaN  0.731  0.731  0.731
Mauritius                                 1.0  0.789 NaN  0.789  0.789  0.789
Mozambique                                1.0  0.684 NaN  0.684  0.684  0.684
Namibia                                   1.0  0.847 NaN  0.847  0.847  0.847
Niger                                     1.0  0.693 NaN  0.693  0.693  0.693
Nigeria                                   1.0  0.878 NaN  0.878  0.878  0.878
Rwanda                                    1.0  0.167 NaN  0.167  0.167  0.167
Senegal                                   1.0  0.801 NaN  0.801  0.801  0.801
Sierra Leone                              1.0  0.866 NaN  0.866  0.866  0.866
South Africa                              1.0  0.860 NaN  0.860  0.860  0.860
Swaziland                                 1.0  0.708 NaN  0.708  0.708  0.708
Tanzania                                  1.0  0.577 NaN  0.577  0.577  0.577
Togo                                      1.0  0.772 NaN  0.772  0.772  0.772
Uganda                                    1.0  0.855 NaN  0.855  0.855  0.855
Zambia                                    1.0  0.823 NaN  0.823  0.823  0.823
Zimbabwe                                  1.0  0.821 NaN  0.821  0.821  0.821


                       75%    max
Country name
Benin                0.661  0.661
Botswana             0.801  0.801
Burkina Faso         0.748  0.748
Burundi              0.607  0.607
Cameroon             0.848  0.848
Chad                 0.807  0.807
Comoros              0.781  0.781
Congo (Brazzaville)  0.745  0.745
Ethiopia             0.761  0.761
Gabon                0.840  0.840
Gambia               0.746  0.746
Ghana                0.848  0.848
Guinea               0.766  0.766
Ivory Coast          0.794  0.794
Kenya                0.825  0.825
Lesotho              0.915  0.915
Liberia              0.850  0.850
Madagascar           0.803  0.803
Malawi               0.729  0.729
Mali                 0.827  0.827
Mauritania           0.731  0.731
Mauritius            0.789  0.789
Mozambique           0.684  0.684
Namibia              0.847  0.847
Niger                0.693  0.693
Nigeria              0.878  0.878
Rwanda               0.167  0.167
Senegal              0.801  0.801
Sierra Leone         0.866  0.866
South Africa         0.860  0.860
Swaziland            0.708  0.708
Tanzania             0.577  0.577
Togo                 0.772  0.772
Uganda               0.855  0.855
Zambia               0.823  0.823
Zimbabwe             0.821  0.821

[36 rows x 24 columns]

In [41]:
history_df[history_df["Regional indicator"] == "South Asia"].groupby("Country name")[["Life Ladder", "Freedom to make life choices", "Perceptions of corruption"]].describe()

             Life Ladder                                                \
                   count   mean std    min    25%    50%    75%    max
Country name
Afghanistan          1.0  2.523 NaN  2.523  2.523  2.523  2.523  2.523
Bangladesh           1.0  5.025 NaN  5.025  5.025  5.025  5.025  5.025
India                1.0  3.819 NaN  3.819  3.819  3.819  3.819  3.819
Maldives             1.0  5.198 NaN  5.198  5.198  5.198  5.198  5.198
Nepal                1.0  5.269 NaN  5.269  5.269  5.269  5.269  5.269
Pakistan             1.0  4.934 NaN  4.934  4.934  4.934  4.934  4.934
Sri Lanka            1.0  4.325 NaN  4.325  4.325  4.325  4.325  4.325

             Freedom to make life choices         ...                \
                                    count   mean  ...    75%    max
Country name                                      ...
Afghanistan                           1.0  0.382  ...  0.382  0.382
Bangladesh                            1.0  0.877  ...  0.877  0.877
India                                 1.0  0.893  ...  0.893  0.893
Maldives                              1.0  0.854  ...  0.854  0.854
Nepal                                 1.0  0.782  ...  0.782  0.782
Pakistan                              1.0  0.726  ...  0.726  0.726
Sri Lanka                             1.0  0.841  ...  0.841  0.841

             Perceptions of corruption                                         \
                                 count   mean std    min    25%    50%    75%
Country name
Afghanistan                        1.0  0.924 NaN  0.924  0.924  0.924  0.924
Bangladesh                         1.0  0.682 NaN  0.682  0.682  0.682  0.682
India                              1.0  0.774 NaN  0.774  0.774  0.774  0.774
Maldives                           1.0  0.825 NaN  0.825  0.825  0.825  0.825
Nepal                              1.0  0.727 NaN  0.727  0.727  0.727  0.727
Pakistan                           1.0  0.787 NaN  0.787  0.787  0.787  0.787
Sri Lanka                          1.0  0.863 NaN  0.863  0.863  0.863  0.863


                max
Country name
Afghanistan   0.924
Bangladesh    0.682
India         0.774
Maldives      0.825
Nepal         0.727
Pakistan      0.787
Sri Lanka     0.863

[7 rows x 24 columns]

# 4.soru cevabı

In [45]:
history_df[history_df["Country name"]=="India"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
732,India,2006,5.348,8.145,0.707,55.720,0.774,NaN,0.855,NaN
733,India,2007,5.027,8.204,0.569,56.140,0.729,-0.051,0.862,NaN
734,India,2008,5.146,8.220,0.684,56.560,0.756,-0.072,0.891,NaN
735,India,2009,4.522,8.281,0.653,56.980,0.679,-0.026,0.895,NaN
736,India,2010,4.989,8.349,0.605,57.400,0.783,0.058,0.863,NaN
737,India,2011,4.635,8.387,0.553,57.700,0.838,-0.038,0.908,NaN
738,India,2012,4.720,8.428,0.511,58.000,0.609,0.067,0.830,NaN
739,India,2013,4.428,8.478,0.553,58.300,0.740,0.084,0.832,NaN
740,India,2014,4.424,8.538,0.621,58.600,0.809,-0.026,0.832,NaN
741,India,2015,4.342,8.604,0.610,58.900,0.777,-0.005,0.776,NaN
742,India,2016,4.179,8.673,0.614,59.300,0.820,0.046,0.765,NaN
743,India,2017,4.046,8.730,0.607,59.700,0.886,-0.042,0.781,NaN
744,India,2018,3.818,8.779,0.638,60.100,0.890,0.085,0.805,NaN
745,India,2019,3.249,8.818,0.561,60.500,0.876,0.112,0.752,NaN
746,India,2020,4.225,8.703,0.617,60.900,0.906,0.075,0.780,NaN
2086,India,2021,3.819,8.755,0.603,60.633,0.893,0.089,0.774,South Asia

In [46]:
history_df[history_df["Country name"]=="Zimbabwe"]

# istenen diğer ülkelerin bilgilerini de aynı şekilde getir.

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
1934,Zimbabwe,2006,3.826,7.711,0.822,41.580,0.431,-0.076,0.905,NaN
1935,Zimbabwe,2007,3.280,7.666,0.828,42.860,0.456,-0.082,0.946,NaN
1936,Zimbabwe,2008,3.174,7.461,0.843,44.140,0.344,-0.090,0.964,NaN
1937,Zimbabwe,2009,4.056,7.563,0.806,45.420,0.411,-0.078,0.931,NaN
1938,Zimbabwe,2010,4.682,7.729,0.857,46.700,0.665,-0.093,0.828,NaN
1939,Zimbabwe,2011,4.846,7.846,0.865,48.120,0.633,-0.088,0.830,NaN
1940,Zimbabwe,2012,4.955,7.983,0.896,49.540,0.470,-0.103,0.859,NaN
1941,Zimbabwe,2013,4.690,7.985,0.799,50.960,0.576,-0.104,0.831,NaN
1942,Zimbabwe,2014,4.184,7.991,0.766,52.380,0.642,-0.074,0.820,NaN
1943,Zimbabwe,2015,3.703,7.992,0.736,53.800,0.667,-0.123,0.810,NaN
1944,Zimbabwe,2016,3.735,7.984,0.768,54.400,0.733,-0.095,0.724,NaN
1945,Zimbabwe,2017,3.638,8.016,0.754,55.000,0.753,-0.098,0.751,NaN
1946,Zimbabwe,2018,3.616,8.049,0.775,55.600,0.763,-0.068,0.844,NaN
1947,Zimbabwe,2019,2.694,7.950,0.759,56.200,0.632,-0.064,0.831,NaN
1948,Zimbabwe,2020,3.160,7.829,0.717,56.800,0.643,-0.009,0.789,NaN
1984,Zimbabwe,2021,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,Sub-Saharan Africa

# 5.soru cevabı

In [49]:
history_df['Perceptions of corruption'].quantile(q=0.75)

# quartile ları bu şekilde belirliyoruz

0.869

In [50]:
history_df['Perceptions of corruption'].quantile(q=0.5)

0.801

In [51]:
history_df['Perceptions of corruption'].quantile(q=0.25)

0.68875

In [57]:
# şimdi bu değer aralıklarını fonksiyonda kullanabiliriz. böylece corruption numerik değerlerini
# descriptive olarak tanımalayacağız.

def trust(corrupt):
    if corrupt >= 0.869000:
        return "Low trust in institutions"
    elif corrupt >  0.801:
        return "Lower than normal level of trust"
    elif 0.801 >= corrupt > 0.68875:
        return "About the normal level trust"
    else :
        return "High level of trust"

In [58]:
history_df["Trust in institutions"] = history_df["Perceptions of corruption"].apply(trust)

# history_df'te Trust in institutions sütunu oluşturup, içine percentions of corruption değerlerinin 
# trust fonksiyonuna uygulanmış halini atadık.

In [60]:
history_df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator,Trust in institutions
0,Afghanistan,2008,3.724,7.370,0.451,50.800,0.718,0.168,0.882,NaN,Low trust in institutions
1,Afghanistan,2009,4.402,7.540,0.552,51.200,0.679,0.190,0.850,NaN,Lower than normal level of trust
2,Afghanistan,2010,4.758,7.647,0.539,51.600,0.600,0.121,0.707,NaN,About the normal level trust
3,Afghanistan,2011,3.832,7.620,0.521,51.920,0.496,0.162,0.731,NaN,About the normal level trust
4,Afghanistan,2012,3.783,7.705,0.521,52.240,0.531,0.236,0.776,NaN,About the normal level trust
...,...,...,...,...,...,...,...,...,...,...,...
2093,China,2021,5.339,9.673,0.811,69.593,0.904,-0.146,0.755,East Asia,About the normal level trust
2094,New Zealand,2021,7.277,10.643,0.948,73.400,0.929,0.134,0.242,North America and ANZ,High level of trust
2095,Australia,2021,7.183,10.796,0.940,73.900,0.914,0.159,0.442,North America and ANZ,High level of trust
2096,Canada,2021,7.103,10.776,0.926,73.800,0.915,0.089,0.415,North America and ANZ,High level of trust
2097,United States,2021,6.951,11.023,0.920,68.200,0.837,0.098,0.698,North America and ANZ,About the normal level trust

# Vectorize'a bak